# Generated by Django 2.2.6 on 2019-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='confDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField(max_length=500)),
                ('confEndDate', models.TextField()),
                ('confStartDate', models.TextField()),
                ('confName', models.CharField(max_length=200)),
                ('venue', models.TextField()),
                ('confUrl', models.URLField()),
            ],
        ),
    ]
