# Generated by Django 2.2.6 on 2019-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0002_auto_20191013_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='confdb',
            name='status',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
